services:
  db:
    image: postgres
    ports:
      - "${HOST_DB_PORT}:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
  web:
    build: .
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    ports:
      - ${HOST_DJANGO_PORT}:8000
    env_file:
      - ./.env
    depends_on:
      - db
