# Generated by Django 5.1.5 on 2025-03-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpage_blogpagerelatedlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="tagline",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
