# Generated by Django 5.1.5 on 2025-03-11 18:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_blogtagindexpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="A brief introduction shown only in lists and previews.",
            ),
        ),
    ]
