# Generated by Django 5.1.5 on 2025-03-01 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_text",
                    models.CharField(blank=True, help_text="Tagline", max_length=255),
                ),
                (
                    "hero_description",
                    models.CharField(
                        blank=True, help_text="Introduction sentenc", max_length=255
                    ),
                ),
                (
                    "hero_cta",
                    models.CharField(
                        blank=True,
                        help_text="Primary Call to Action text",
                        max_length=255,
                        verbose_name="Primary CTA",
                    ),
                ),
                ("hero_cta_link", models.URLField(blank=True)),
                (
                    "secondary_action_label",
                    models.CharField(
                        blank=True,
                        help_text="Secondary Action label",
                        max_length=255,
                        verbose_name="Secondary Action Label",
                    ),
                ),
                ("secondary_action_link", models.URLField(blank=True)),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Homepage hero image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
