# Generated by Django 5.1.5 on 2025-03-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_mainnavitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainnavitem",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
