# Generated by Django 5.1.5 on 2025-03-01 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_mainnavitem_order"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainnavitem",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Used to determine order when rendering"
            ),
        ),
        migrations.AlterField(
            model_name="mainnavitem",
            name="page",
            field=models.ForeignKey(
                blank=True,
                help_text="Will be overridden by External URL if one is provided",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Internal Page",
            ),
        ),
    ]
