# Generated by Django 5.1.5 on 2025-03-02 02:57

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_mainnavitem_order_alter_mainnavitem_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="catalog_body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="catalog_cta",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Catalog CTA"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="catalog_cta_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="catalog_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Catalog Section Title"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="community_body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="community_cta",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Community CTA"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="community_cta_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="community_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Community Section Title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_description",
            field=models.CharField(
                blank=True, help_text="Introductory sentence", max_length=255
            ),
        ),
    ]
