# Generated by Django 5.1.5 on 2025-03-01 14:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ckan_url",
                    models.URLField(blank=True, null=True, verbose_name="CKAN URL"),
                ),
                (
                    "dathere_url",
                    models.URLField(blank=True, null=True, verbose_name="DatHere URL"),
                ),
                (
                    "pitt_url",
                    models.URLField(blank=True, null=True, verbose_name="Pitt URL"),
                ),
                (
                    "wprdc_url",
                    models.URLField(blank=True, null=True, verbose_name="WPRDC URL"),
                ),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub URL")),
                (
                    "nsf_url",
                    models.URLField(blank=True, null=True, verbose_name="NSF URL"),
                ),
                ("partner_text", wagtail.fields.RichTextField(blank=True)),
                ("funding_text", wagtail.fields.RichTextField(blank=True)),
                (
                    "ckan_logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="CKAN logo image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="CKAN logo",
                    ),
                ),
                (
                    "dathere_logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="DatHere logo image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="DatHere logo",
                    ),
                ),
                (
                    "nsf_logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="NSF logo image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="NSF logo",
                    ),
                ),
                (
                    "pitt_logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pitt logo image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Pitt logo",
                    ),
                ),
                (
                    "wprdc_logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="WPRDC logo image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="WPRDC logo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
