# Generated by Django 5.1.5 on 2025-03-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_mainnavitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MainNavItem",
        ),
    ]
