# Generated by Django 5.1.5 on 2025-03-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_globalsettings_funding_text_footertext_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HighlightedExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=255, verbose_name="Extension ID")),
            ],
        ),
        migrations.CreateModel(
            name="HighlightedSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=255, verbose_name="Site ID")),
            ],
        ),
    ]
