# Generated by Django 5.1.7 on 2025-03-18 14:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_highlightedextension_highlightedsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightedextension',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highlightedsite',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
