# Generated by Django 5.1.7 on 2025-03-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_highlightedextension_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlightedextension',
            name='description',
        ),
        migrations.RemoveField(
            model_name='highlightedsite',
            name='description',
        ),
    ]
