# Generated by Django 5.1.7 on 2025-03-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_highlightedextension_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightedDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.IntegerField(verbose_name='Topic ID')),
                ('topic_name', models.CharField(max_length=255, verbose_name='Topic Name')),
            ],
        ),
    ]
