# Generated by Django 5.1.7 on 2025-03-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_highlighteddiscussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlighteddiscussion',
            name='topic_id',
            field=models.IntegerField(help_text='For internal use only, widget will use data from discourse', verbose_name='Topic ID'),
        ),
    ]
