# Generated by Django 5.1.7 on 2025-03-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_highlighteddiscussion_topic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlighteddiscussion',
            name='topic_id',
            field=models.IntegerField(verbose_name='Topic ID'),
        ),
        migrations.AlterField(
            model_name='highlighteddiscussion',
            name='topic_name',
            field=models.CharField(help_text='For internal use only, widget will use data from discourse', max_length=255, verbose_name='Topic Name'),
        ),
    ]
